export {default as Hero} from "./Hero"
export {default as Programs} from "./Programs"
export {default as Team} from "./Team"
export {default as Blogs} from "./Blogs"
export {default as News} from "./News"
