import React from "react";
import { Header, CardSection,OtherTopics } from "../../container/emotional";
import Hero from "../../component/hero/Hero";
import { emotional } from "@/assets/images/emotional";
import ExploreTopics from "@/component/ExploreTopics";
import { reading } from "@/assets/images/emotional";
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Ethnical Support',
  description: 'Generated by create next app',
}

function page() {
    return (
        <div>
            <Hero title={"emotional and ethical  support"} />
            <Header
                title={"EMOTIONAL & ETHICAL SUPPORT"}
                content={[
                    "Our GGS incorporates and ensures that well being is intrinsically linked to all aspects of learner’s experience at school and beyond. ",
                    <br></br>,
                    <br></br>,
                    " Our facilitators nurture the and develop physical, emotional, cognitive, spiritual and social health of the ggians and make them Internationally thought people and a great citizen. Every learner’s holistic well being is implicitly and explicitly addressed through words of encouragement and constant motivation.",
                    <br></br>,
                    <br></br>,
                    " Social and emotional learning is the process of developing self-awareness, self control, and interpersonal skills that are necessary for resilience, wellbeing, and overall life satisfaction. This can be achieved through the practice of student agency.   ",
                ]}
                img={emotional}
            />
            <CardSection />
            <Header
                title={"THROUGH STUDENT AGENCY"}
                content={[
                    "Learners take initiative, express interest and wonderings, make choices and are aware of their learning goals. They are active, engaged, monitor and adjust their learning as needed. They offer feedback to others and consult on decisions that affect them.",
                    <br></br>,
                    <br></br>,
                    " They also take responsibility for their learning and collaborate with facilitators and peers to plan, present and assess learning needs.",
                    <br></br>,
                    <br></br>,
                    "Our facilitators recognize learners’ capabilities through listening, respecting and responding to their ideas. They make thoughtful considerations and decisions with an emphasis on relationships.",
                ]}
                img={reading}
                rev={true}
            />{" "}
            <ExploreTopics />
        </div>
    );
}

export default page;
