import {Cards, Description,Others} from "@/container/why-us"
import Hero from "../../component/hero/Hero"
import { ExploreTopics } from "@/component"
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Why us',
  description: 'Generated by create next app',
}
const Whyus = () => {
  return (
    <div>
      <Hero title={"WHY US"}/>
      <Description/>
      <Cards/>
      <ExploreTopics />
    </div>
  )
}

export default Whyus
