import {Description, Listofevents, Slideshow} from "@/container/events"
import {Others} from "@/container/work-with-us"
import Hero from "../../component/hero/Hero";
import ExploreTopics from "@/component/ExploreTopics";
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Days & Events',
  description: 'Generated by create next app',
}

const Page = () => {
  return (
    <div>
        <Hero title={"days and events"} />
        <Listofevents/>
        <Slideshow/>
        <ExploreTopics />
    </div>
  )
}

export default Page
