import { DescriptionBox,Content, Others } from "@/container/work-with-us"
import Hero from "../../component/hero/Hero"
import { ExploreTopics } from "@/component"
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Work with us',
  description: 'Generated by create next app',
}
const Works = () => {
  return (
    <div>
      <Hero title={"Work with us"}/>
      <DescriptionBox/>
      <Content/>
      <ExploreTopics />
    </div>
  )
}

export default Works
