import React from "react";

import { Head } from "../../container/policies";
import Description from "../../container/policies/Description";
import PoliciesFlex from "../../container/policies/PoliciesFlex"
import OtherTopics from "../../container/policies/OtherTopics"

import Enquire from "../../component/Enquire/Enquire"
import Hero from "../../component/hero/Hero"
import ExploreTopics from "@/component/ExploreTopics";
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Policies',
  description: 'Generated by create next app',
}
function page() {

  const Headings = ["Admission Policy","Language Policy", "Assessment Policy","Inclusive Education Policy","Academic Integrity Policy"]
  const Links = [
    "https://drive.google.com/file/d/1jQcfIlCm-1HvKUmoX0x6vAM0Xpoh-HyG/view?usp=drive_link",
    "https://drive.google.com/file/d/1VivqCAqS16PP8hJju4-rPP3Xizgz7B6-/view?usp=drive_link",
    "https://drive.google.com/file/d/19XB61l8zJTppU6NotQ6nAXwIk4-_AqCL/view?usp=drive_link",
    "https://drive.google.com/file/d/14uE4QMOo7GyhlJCc047wMS4dAECq_thQ/view?usp=drive_link",
    "https://drive.google.com/file/d/1f0jipdAUxho-i5xNIZNHfMTqqApJzqBR/view?usp=drive_link",
  ]

  return (
    <>
      <Hero title={"Policies"}/>
      <Head />
      <Description />
      <section className="section-container">
        <h2 className="text-heading-4 md:text-heading-3 uppercase lg:w-[90%] text-primary-maroon-1 mb-xl">
          list of policies
        </h2>
        <p className="text-body mb-xl">
          Every year, these policies will be reviewed along with the members of
          the school community to enhance for betterment.
        </p>
        <PoliciesFlex headings={Headings} links={Links} />

      </section>
      <ExploreTopics />
    </>
  );
}

export default page;
