import React from "react";
import Image from "next/image";
import eypLogo from "../../assets/eyp image 1.jpg";
import eypLogo2 from "../../assets/Group 24.png";
import TopicCard from "@/component/topicsCard/TopicCard";
import Hero from "../../component/hero/Hero";
import FormatQuoteIcon from '@mui/icons-material/FormatQuote';
import {EarlyYears, Offers} from "@/container/eyp/";
import {eyp, features, pyp, offer_1, offer_2, offer_3, offer_4, offer_5} from "@/assets/images/curriculum";
import ExploreTopics from "@/component/ExploreTopics";
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Curriculum',
  description: 'Generated by create next app',
}

function page() {
    return (
        <>
            <Hero title={"CURRICULAM AND LEARNING"} />
            <section className="relative section-container bg-primary-maroon-1 ">
                <div className="absolute top-0 left-0 z-0">
                    <FormatQuoteIcon sx={{ fontSize: 150, opacity: 0.2, color: "#F05A22"}} />
                </div>
                <p className="text-heading-6 uppercase text-white z-10">
                    Our goal is to promote <span className="text-primary-yellow-1">“International mindedness”</span>, manifesting a sense of morality to all the human beings in the global society.
                </p>
            </section>

            <section className="section-container w-full flex flex-col md:flex-row gap-5 md:gap-xl">
                <div className="w-full md:w-1/2">
                    <Image
                        src={pyp}
                        className="w-full h-full object-cover"
                        alt="logo"
                        unoptimized
                    />
                </div>
                <div className="w-full md:w-1/2">
                    <h2 className="text-primary-maroon-1 text-heading-3 mb-large uppercase">
                        PRIMARY YEAR PROGRAMME
                    </h2>
                    <h4 className="text-heading-6 p-md bg-primary-maroon-1 text-white mb-large">
                        Curiosity is the fuel for discovery, inquiry and learning
                    </h4>
                    <div className="flex flex-col gap-large text-body">
                        <p>
                            Children are natural inquirers from birth; they have
                            the capacity to learn about, interact with, and
                            interpret the world around them.
                        </p>
                        <p>
                            From birth, children possess all kinds of mental
                            abilities uniquely suited to these early phases of
                            learning and development.
                        </p>
                        <p>
                            They are curious and capable learners with a sense
                            of agency, rich in potential, bringing valid skills,
                            preferences, and understanding to the educational
                            process.
                        </p>
                    </div>
                </div>
            </section>

            <Offers />

            <section className="section-container py-0">
                <div className="bg-primary-yellow-1 p-xl">
                    <h2 className="text-primary-maroon-1 text-heading-3 uppercase text-center">
                        SHARPING YOUNG MINDS
                    </h2>
                </div>
            </section>

            <section className="section-container w-full flex flex-col md:flex-row gap-5 md:gap-xl">
                <div className="w-full md:w-1/2">
                    <Image
                        src={eyp}
                        className="w-full h-full object-cover"
                        alt="logo"
                        unoptimized
                    />
                </div>
                <div className="w-full md:w-1/2">
                    <h2 className="text-primary-maroon-1 text-heading-3 mb-large uppercase">
                        EARLY YEAR PROGRAMME
                    </h2>
                    <h4 className="text-heading-6 p-md bg-primary-maroon-1 text-white mb-large">
                        A child’s learning begins from early years.
                    </h4>
                    <div className="flex flex-col gap-large text-body">
                        <p>
                            Children are natural inquirers from birth; they have
                            the capacity to learn about, interact with, and
                            interpret the world around them.
                        </p>
                        <p>
                            From birth, children possess all kinds of mental
                            abilities uniquely suited to these early phases of
                            learning and development.
                        </p>
                        <p>
                            They are curious and capable learners with a sense
                            of agency, rich in potential, bringing valid skills,
                            preferences, and understanding to the educational
                            process.
                        </p>
                    </div>
                </div>
            </section>

            <section className="section-container flex flex-col md:flex-row gap-5 md:gap-xl">
                <div className="w-full md:w-1/2">
                    <p className="text-primary-maroon-1 text-heading-3 mb-large uppercase">
                        FEATURES
                    </p>
                    <div className="flex flex-col gap-large text-body">
                        <p>
                            Learning spaces at GGS are designed to support
                            active participation of children through play.
                        </p>
                        <p>
                            Learning engagements and classroom activities are
                            designed by teachers to develop their fine and gross
                            motor skills in everyday teaching and learning.
                        </p>
                        <p>
                            Literacy and Numeracy curriculum are framed through
                            a wide range of playful and inquiry-based
                            explorations. Learners are provided with various
                            symbolic and representational learning.
                        </p>
                        <p>
                            Learner’s are provided with various symbolic and representational learning.
                        </p>
                    </div>
                </div>
                <div className="w-full md:w-1/2">
                    <Image
                        src={features}
                        alt="logo"
                        className="w-full h-auto"
                        unoptimized
                    />
                </div>
            </section>

            {/* PROGRAMS STECTION */}
            <EarlyYears />

            {/* other topics to explore */}

            <ExploreTopics />
        </>
    );
}

export default page;
