import React from "react";
import { Header, Profile, OtherTopics } from "../../container/MissionVision";
import Hero from "../../component/hero/Hero";
import ExploreTopics from "@/component/ExploreTopics";
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Mission & Values',
  description: 'Generated by create next app',
}

function page() {
    return (
        <>
            <Hero title={"Mission & Values"} />
            <Header />
            <Profile />
            <ExploreTopics />
        </>
    );
}

export default page;
