import React from "react";
import Hero from "../../component/hero/Hero";
import type { Metadata } from "next";
import { EventList } from "@/container/discovery";

export const metadata: Metadata = {
    title: "Discover",
    description: "Generated by create next app",
};

function page() {
    return (
        <div>
            <Hero title="DISCOVERY OUTSIDE THE WALL" />
            <section className="section-container my-6">
                <EventList />
            </section>
        </div>
    );
}

export default page;
