import Hero from "../../component/hero/Hero"
import { Cards, Curriculum } from "@/container/awakening-creativity";
import ExploreTopics from "@/component/ExploreTopics";
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Awakening Creativity',
  description: 'Generated by create next app',
}

const AwakeningCreativity = () => {

  return (
    <>
      <Hero title={"Health & WELL BEING"}/>
      <Cards />
      <Curriculum />
      <ExploreTopics />
    </>
  );
};

export default AwakeningCreativity;
