import React from "react";
import StudioCards from "../../container/life-at-ggs/StudioCards";
import Hero from "../../component/hero/Hero";
import FormatQuoteIcon from "@mui/icons-material/FormatQuote";
import * as cardImages from "@/assets/images/life-at-ggs"
import ExploreTopics from "@/component/ExploreTopics";
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Life at GGS',
  description: 'Generated by create next app',
}
// md:p-md lg:p-large xl:p-xl 2xl:p-2xl 3xl:p-3xl

function page() {
  const studios = [
    {
      images: [cardImages.sports],
      name: "SPORTS",
      text: [
        "We believe that sports is vital for students’ physical and social well-being.",
        "It helps develop values of sportsmanship, trust and cooperation.",
        "We include a range of activities like swimming, gymnastics, basketball and adventure challenging activities. It develops their leadership, accountability, team work, social skills.",
      ],
    },
    {
      images: [cardImages.performing_art1, cardImages.performing_art2, cardImages.performing_art3],
      name: "PERFORMING ARTS",
      text: [
        "We tap into the rich cultural experiences of our students’ creativity and performance through dance, music and drama.",
        "Our agentic students are given opportunities to explore and express their ideas to discover their hidden talents in performing art.",
      ],
    },
    {
      images: [cardImages.visual_art, cardImages.visual1,cardImages.visual2],
      name: "VISUAL ARTS",
      text: [
        "We enrich the young minds with art and craft. We celebrate passion, creativity, knowledge and skills of students.",
        "The visual arts studio is a place to explore, discover and develop their own creative expressions.",
        "It is the place where they connect themselves to the real world through colours, shapes, patterns using the different art forms.",
      ],
    },
    {
      images: [cardImages.design_thinking1, cardImages.design_thinking2, cardImages.design_thinking3],
      name: "Design THINKING & TECHNOLOGY",
      text: [
        "The Science, Technology, Engineering and Mathematics education prepares our students for the future. The hands-on experience and real - world application help them become able leaders, innovators, risk-takers and problem solvers.",
        "Technology is a powerful tool in 21st century education. Students use iPads ethically to enhance their research skills. It helps them to collaborate and reflect their learning. The versatile teaching and learning apps make the students to embrace the digital age as a foundation for a sustainable education. This enables them to understand and follow integrity during their learning process.",
      ],
    },
    {
      images: [cardImages.book_studio1, cardImages.book_studio2],
      name: "BOOKS",
      text: [
        "Reading makes every person an independent capable learner by cultivating one’s imagination. Our library is an exciting and welcoming place that supplements the learning needs of all students. We have a repository of books to help every member of the school community to gain new knowledge, skills and dispositions.",
      ],
    },
  ];

  return (
    <>
      <Hero title={"LIFE @ GGS"} />
      <section className="relative section-container bg-primary-maroon-1 ">
        <div className="absolute top-0 left-0 z-0">
          <FormatQuoteIcon
            sx={{ fontSize: 150, opacity: 0.2, color: "#F05A22" }}
          />
        </div>
        <p className="text-heading-6 uppercase text-white z-10">
          Teach your child the art of learning through creativity and curiosity.
        </p>
      </section>

      {/* our facility */}
      <section className="section-container">
        <h2 className="text-heading-4 md:text-heading-3 uppercase lg:w-[90%] text-primary-maroon-1 mb-md">
          OUR FACILITIES
        </h2>
        <p className="text-body">
          Good infrastructure and facilities encourage children's to feel warm and
          welcoming in the school. They also provide various Opportunities to
          explore and learn new skills.
        </p>
      </section>

      {/* studio section  */}
      <section className="">
        {studios.map((item, index) => (
          <StudioCards
            className={`section-container flex flex-col justify-between gap-5 md:gap-28 ${
              index % 2 == 1
                ? "bg-primary-yellow-2 md:flex-row-reverse"
                : "md:flex-row"
            }`}
            img={item.images}
            name={item.name}
            text={item.text}
            key={index}
          />
        ))}
      </section>
      {/* other topics */}
      <ExploreTopics />
    </>
  );
}

export default page;
