import {DescriptionBox,Council,Teamcard,Content,Benefits, Others} from  "@/container/student-council"
import Hero from "../../component/hero/Hero"
import { ExploreTopics } from "@/component"
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Student Council',
  description: 'Generated by create next app',
}
const StudentCouncil = () => {
  return (
    <div>
      <Hero title={"Student Leadership"}/>
      <DescriptionBox/>
      <Council/>
      <Teamcard/>
      <Content/>
      <Benefits/>
      <ExploreTopics />
    </div>
  )
}

export default StudentCouncil
