import { Enquiry, Quotebox, Faq, Admissionpolicy } from "@/container/Admission";
import { Others } from "@/container/work-with-us";
import Hero from "../../component/hero/Hero";
import ExploreTopics from "@/component/ExploreTopics";
import type { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'Admission',
    description: 'Generated by create next app',
}

const Admission = () => {
    return (
        <div>
            <Hero title={"Admissions"} />
            <Quotebox />
            <Enquiry />
            <Admissionpolicy />
            <Faq />
            <ExploreTopics />
        </div>
    );
};

export default Admission;
